#!python

import ccxt
import secrets
import sys

conn = ccxt.kraken({
        "apiKey" : secrets.publickey,
        "secret" : secrets.privatekey
})

def greentext(s):
    coloring = '\x1b[1;32;40m'
    ending = '\x1b[0m'
    return coloring + s + ending

def yellowtext(s):
    coloring = '\x1b[1;33;40m'
    ending = '\x1b[0m'
    return coloring + s + ending

def greenbg(s):
    coloring = '\x1b[6;30;42m'
    ending = '\x1b[0m'
    return coloring + s + ending

bals = conn.fetchBalance()['free']
coins = list(bals.keys())
tick = conn.fetchTickers()

print('')
print("CHECKING IN!  Currently, your wallet holds:")

total_value = 0
for c in coins:
    if c == 'USD':
        print(greentext("   %5.2f USD") % bals['USD'])
        total_value += bals['USD']
    else:
        bal = bals[c]
        pr = tick[c + '/USD']['last']
        value = bal * pr
        total_value += value
        print(yellowtext("%1.6f %s (worth %2.2f USD)") % (bal, c, value))

print('')
print("TOTAL WALLET VALUE:")
print(greenbg("%5.2f USD") % total_value)
